variable "vpc_id" {}
variable "subnet_ids" {}
variable "parameter_group_family" {}
variable "identifier" {}
variable "common_tags" {}
variable "cidrs" {}
variable "allocated_storage" {}
variable "allow_major_version_upgrade" {}
variable "apply_immediately" {}
variable "auto_minor_version_upgrade" {}
variable "availability_zone" {}
variable "backup_retention_period" {}
variable "backup_window" {}
variable "copy_tags_to_snapshot" {}
variable "db_name" {}
variable "deletion_protection" {}
variable "rds_engine_name" {}
variable "rds_engine_version" {}
variable "instance_class" {}
variable "iops" {}
variable "maintenance_window" {}
variable "max_allocated_storage" {}
variable "multi_az" {}
variable "rds_port" {}
variable "snapshot_identifier" {}
variable "storage_encrypted" {}
variable "storage_type" {}
variable "username" {}