name: my first workflow
env:
 NAME: 'My Actions'
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  simple-test:
    env:
     JAVA_VERSION: '1.1'
    runs-on: ubuntu-latest
    steps:
     - name: A job to run shell commands
       run: |
        echo "Hello, GitHub Actions!"
        echo "This is my first workflow"
        echo "print ${{ github.repository }}, ${{ github.action }}"
        echo "This job is triggered by ${{ github.event_name }}"
     - name: Checkout code
       uses: actions/checkout@v2
     - name: terraform formate
       run: |
         sh test-script.sh
         cd aws-ec2-module
         terraform fmt
         echo "Hello $NAME. $BUILD. Using Java Version $JAVA_VERSION"
         echo "::debug::executing the setup script"
       env:
          BUILD: 'We are currently running the Build Job'
